name: Deploy to Live Channel

on:
  push:
    branches:
      - master
    # Optionally configure to run only for specific files. For example:
    # paths:
    # - "website/**"

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: npm install && npm run build --prefix client

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}"
          expires: 30d
          projectId: ${{ secrets.FIREBASE_PROJECT_ID }}
          channelId: live
